<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Room;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

/**
 * ScrapedDataSeeder
 * Dữ liệu phòng trọ thực lấy từ phongtro123.com (tháng 4/2026)
 * Khu vực: TP. Vinh - Nghệ An, Hà Nội, TP. Hồ Chí Minh
 */
class ScrapedDataSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('🌐 Seeding dữ liệu thực từ phongtro123.com...');

        $this->command->info('👤 Tạo chủ trọ đại diện...');
        $landlords = $this->seedScrapedLandlords();

        $this->command->info('🏠 Tạo phòng trọ thực...');
        $this->seedScrapedRooms($landlords);

        $this->command->info('✅ Hoàn tất! Đã seed dữ liệu thực từ phongtro123.com.');
    }

    private function seedScrapedLandlords(): array
    {
        $data = [
            [
                'name'          => 'Chủ trọ Vinh - Nghệ An',
                'email'         => 'landlord.vinh@phongtro123.test',
                'phone'         => '0912000001',
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
            ],
            [
                'name'          => 'Chủ trọ Hà Nội',
                'email'         => 'landlord.hanoi@phongtro123.test',
                'phone'         => '0912000002',
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Cầu Giấy',
            ],
            [
                'name'          => 'Chủ trọ Sài Gòn',
                'email'         => 'landlord.saigon@phongtro123.test',
                'phone'         => '0912000003',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 1',
            ],
        ];

        $landlords = [];
        foreach ($data as $d) {
            $landlords[$d['province_name']] = User::updateOrCreate(
                ['email' => $d['email']],
                [
                    'name'          => $d['name'],
                    'phone'         => $d['phone'],
                    'password'      => Hash::make('password'),
                    'role'          => 'landlord',
                    'province_name' => $d['province_name'],
                    'district_name' => $d['district_name'],
                ]
            );
        }

        return $landlords;
    }

    private function seedScrapedRooms(array $landlords): void
    {
        // =============================================
        // DỮ LIỆU THỰC TỪ PHONGTRO123.COM (04/2026)
        // =============================================
        $rooms = [

            // ==================== NGHỆ AN - TP. VINH ====================
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Lê Mao',
                'address_detail'=> '21 Nguyễn Xiển, Thành Phố Vinh, Nghệ An',
                'name'          => 'Cho thuê phòng trọ 21 Nguyễn Xiển, ngay mặt tiền trung tâm chợ Vinh',
                'price'         => 1500000,
                'area'          => 15,
                'description'   => 'Phòng trọ khép kín, sạch sẽ, an ninh tốt ngay trung tâm chợ Vinh. Gần siêu thị, chợ, trường học. Có chỗ để xe.',
                'amenities'     => ['Wifi', 'Chỗ để xe', 'An ninh 24/7'],
                'latitude'      => 18.6762,
                'longitude'     => 105.6855,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Hưng Dũng',
                'address_detail'=> 'Nguyễn Gia Thiều, Hưng Dũng, Thành Phố Vinh, Nghệ An',
                'name'          => 'Cho thuê phòng trọ 35m2 Nguyễn Gia Thiều, Hưng Dũng',
                'price'         => 1800000,
                'area'          => 35,
                'description'   => 'Phòng rộng rãi, thoáng mát, phù hợp sinh viên hoặc hộ gia đình nhỏ. Điện nước giá dân, WC riêng.',
                'amenities'     => ['WC riêng', 'Nước nóng', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 18.6648,
                'longitude'     => 105.6795,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Vinh Tân',
                'address_detail'=> 'Phường Vinh Tân, Thành Phố Vinh, Nghệ An',
                'name'          => 'Cho thuê phòng trọ khép kín phường Vinh Tân',
                'price'         => 1500000,
                'area'          => 20,
                'description'   => 'Phòng khép kín đầy đủ tiện nghi tại phường Vinh Tân, TP Vinh. Điện 4.000đ/kWh, nước 15.000đ/m3.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 18.6735,
                'longitude'     => 105.6920,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Nghi Phú',
                'address_detail'=> 'Đường Trần Đình Quán, Nghi Phú, Vinh, Nghệ An',
                'name'          => 'Cho thuê phòng trọ tại đường Trần Đình Quán, Nghi Phú, Vinh',
                'price'         => 2500000,
                'area'          => 22,
                'description'   => 'Gần BV Ba Lan, BV 115, BV Răng Hàm Mặt, vị trí thuận tiện. Phòng khép kín có điều hòa, nước nóng.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 18.6825,
                'longitude'     => 105.6750,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Hưng Bình',
                'address_detail'=> 'Hưng Bình, Vinh, Nghệ An',
                'name'          => 'Phòng trọ khép kín Vinh Nghệ An, diện tích 35m2 có gác lửng 15m2',
                'price'         => 2000000,
                'area'          => 35,
                'description'   => 'Có gác lửng, sạch sẽ, gần Ga Vinh, VSIP Nghệ An. Không gian rộng rãi cho 1-2 người ở.',
                'amenities'     => ['Gác xép', 'WC riêng', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 18.6680,
                'longitude'     => 105.6870,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Quán Bàu',
                'address_detail'=> 'Phường Quán Bàu, Vinh, Nghệ An',
                'name'          => 'Phòng gia đình 40m2, điện nước giá nhà nước, khu dân cư yên tĩnh',
                'price'         => 2200000,
                'area'          => 40,
                'description'   => 'Phòng rộng cho gia đình, dân cư yên tĩnh, gần chợ và trường học. Điện nước tính giá nhà nước.',
                'amenities'     => ['WC riêng', 'Nước nóng', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 18.6695,
                'longitude'     => 105.6945,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Lê Mao',
                'address_detail'=> '07 Nguyễn Xiển, Vinh, Nghệ An',
                'name'          => 'Phòng trọ khép kín full nội thất tại Vinh - Nguyễn Xiển',
                'price'         => 3000000,
                'area'          => 25,
                'description'   => 'Đầy đủ nội thất, điều hòa, tủ lạnh, chỉ việc xách vali vào ở. Phòng đẹp, mới, sạch sẽ.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Tủ lạnh', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 18.6762,
                'longitude'     => 105.6855,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Trường Thi',
                'address_detail'=> 'Gần ĐH Vinh, Đường Lê Viết Thuật, Vinh, Nghệ An',
                'name'          => 'Chính chủ cho thuê phòng trọ khép kín gần ĐH Vinh',
                'price'         => 1200000,
                'area'          => 18,
                'description'   => 'Giá rẻ cho sinh viên, sạch sẽ, an ninh. Gần trường ĐH Vinh, ĐH Sư phạm Kỹ thuật.',
                'amenities'     => ['Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 18.6703,
                'longitude'     => 105.6732,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Hà Huy Tập',
                'address_detail'=> 'Tạ Quang Bửu, TP Vinh, Nghệ An',
                'name'          => 'Cho thuê phòng trọ thoáng mát, có điều hòa, an ninh tốt - Tạ Quang Bửu',
                'price'         => 1700000,
                'area'          => 25,
                'description'   => 'Phòng có điều hòa, thoáng mát, khu dân trí cao. Điện 3.500đ/kWh, nước 15.000đ/m3.',
                'amenities'     => ['Điều hòa', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 18.6790,
                'longitude'     => 105.6813,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Cửa Nam',
                'address_detail'=> 'Gần bệnh viện TP.Vinh, Nghệ An',
                'name'          => 'Cho thuê phòng trọ khép kín gần bệnh viện TP.Vinh',
                'price'         => 1200000,
                'area'          => 20,
                'description'   => 'Tiện cho người nhà bệnh nhân hoặc nhân viên y tế. Gần BV Hữu Nghị Đa Khoa Nghệ An.',
                'amenities'     => ['WC riêng', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 18.6825,
                'longitude'     => 105.6750,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Lê Lợi',
                'address_detail'=> 'Đường Lê Lợi, Thành phố Vinh, Nghệ An',
                'name'          => 'Phòng trọ cho thuê khép kín, đầy đủ nóng lạnh, điều hòa - Lê Lợi',
                'price'         => 2000000,
                'area'          => 20,
                'description'   => 'Đầy đủ tiện nghi nóng lạnh điều hòa, phòng mới đẹp. Chuyên cung cấp dịch vụ cho thuê tại TP Vinh.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 18.6762,
                'longitude'     => 105.6855,
            ],
            [
                'province_name' => 'Tỉnh Nghệ An',
                'district_name' => 'Thành phố Vinh',
                'ward_name'     => 'Phường Bến Thủy',
                'address_detail'=> 'Đường Nguyễn Du, Bến Thủy, Vinh, Nghệ An',
                'name'          => 'Phòng trọ đường Nguyễn Du, Bến Thủy - Điện nước giá dân',
                'price'         => 1500000,
                'area'          => 18,
                'description'   => 'Phòng đẹp, mới xây, điện nước giá dân. Khu dân cư yên tĩnh, an ninh tốt.',
                'amenities'     => ['Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 18.6610,
                'longitude'     => 105.6988,
            ],

            // ==================== HÀ NỘI ====================
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Nam Từ Liêm',
                'ward_name'     => 'Phường Cầu Diễn',
                'address_detail'=> 'Ngõ 63 Nguyễn Văn Giáp, Nam Từ Liêm, Hà Nội',
                'name'          => 'Cho thuê phòng đủ đồ ngõ 63 Nguyễn Văn Giáp - Hàm Nghi - Vinhomes Gardenia',
                'price'         => 4500000,
                'area'          => 28,
                'description'   => 'Full nội thất, gần Vinhomes Gardenia thuận tiện đi lại. Điều hòa, tủ lạnh, máy giặt chung.',
                'amenities'     => ['Điều hòa', 'Tủ lạnh', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 21.0227,
                'longitude'     => 105.7696,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Ba Đình',
                'ward_name'     => 'Phường Cống Vị',
                'address_detail'=> 'Cống Vị, Ba Đình, Hà Nội',
                'name'          => 'Cho thuê phòng khép kín Full nội thất, ban công thoáng - Ba Đình',
                'price'         => 5800000,
                'area'          => 27,
                'description'   => 'Phòng đẹp, nội thất cao cấp sang trọng, khu dân trí cao. Ban công thoáng, view đẹp.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Tủ lạnh', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 21.0369,
                'longitude'     => 105.8333,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Cầu Giấy',
                'ward_name'     => 'Phường Dịch Vọng Hậu',
                'address_detail'=> 'Dịch Vọng Hậu, Cầu Giấy, Hà Nội',
                'name'          => 'Phòng trọ khu vực Cầu Giấy - Giá rẻ gần các trường đại học',
                'price'         => 2500000,
                'area'          => 20,
                'description'   => 'Phòng trọ giá sinh viên, sạch sẽ, gần các trường đại học. Gần ĐH Quốc Gia, ĐH Khoa Học Tự Nhiên.',
                'amenities'     => ['Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 21.0409,
                'longitude'     => 105.7895,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Long Biên',
                'ward_name'     => 'Phường Thượng Thanh',
                'address_detail'=> 'Ngõ 68/188 Nguyễn Văn Linh, Long Biên, Hà Nội',
                'name'          => 'Cho thuê phòng trọ tại ngõ 68/188 Nguyễn Văn Linh, Long Biên',
                'price'         => 3000000,
                'area'          => 28,
                'description'   => 'Không gian thoáng mát, điện nước giá dân. Gần khu công nghiệp Long Biên.',
                'amenities'     => ['WC riêng', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 21.0638,
                'longitude'     => 105.8878,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Hoàng Mai',
                'ward_name'     => 'Phường Yên Sở',
                'address_detail'=> 'Khu TĐC X2A Yên Sở, Hoàng Mai, Hà Nội',
                'name'          => 'Cho thuê phòng khu TĐC X2A Yên Sở, Hoàng Mai',
                'price'         => 3300000,
                'area'          => 35,
                'description'   => 'Phòng rộng, thoáng mát, khu vực an ninh cực tốt. Gần Công viên Yên Sở.',
                'amenities'     => ['WC riêng', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 20.9847,
                'longitude'     => 105.8556,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Hoàng Mai',
                'ward_name'     => 'Phường Định Công',
                'address_detail'=> 'Định Công, Hoàng Mai, Hà Nội',
                'name'          => 'Cho thuê phòng khép kín, có gác xép - Hoàng Mai',
                'price'         => 1700000,
                'area'          => 20,
                'description'   => 'Giá cực rẻ, có thêm gác xép để đồ rất tiện lợi. Phù hợp sinh viên đi làm.',
                'amenities'     => ['Gác xép', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 20.9910,
                'longitude'     => 105.8332,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Hà Đông',
                'ward_name'     => 'Phường Dương Nội',
                'address_detail'=> 'Dương Nội, Hà Đông, Hà Nội',
                'name'          => 'Phòng trọ mới xây tại Hà Đông, giá sinh viên',
                'price'         => 2000000,
                'area'          => 20,
                'description'   => 'Phòng mới tinh, khép kín, gần Học viện Bưu Chính Viễn Thông và ĐH Kiến Trúc.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 20.9820,
                'longitude'     => 105.7703,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Hai Bà Trưng',
                'ward_name'     => 'Phường Bách Khoa',
                'address_detail'=> 'Bách Khoa, Hai Bà Trưng, Hà Nội',
                'name'          => 'Cho thuê phòng trọ gần Đại học Bách Khoa Hà Nội',
                'price'         => 2800000,
                'area'          => 18,
                'description'   => 'Vị trí đắc địa, gần trường học, chợ và bến xe. Khu dân cư văn minh, an ninh.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 21.0070,
                'longitude'     => 105.8425,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Đống Đa',
                'ward_name'     => 'Phường Phương Mai',
                'address_detail'=> 'Phương Mai, Đống Đa, Hà Nội',
                'name'          => 'Phòng trọ mini đầy đủ tiện nghi tại Đống Đa',
                'price'         => 4000000,
                'area'          => 22,
                'description'   => 'Nội thất cơ bản đầy đủ, ngay khu trung tâm quận Đống Đa. Gần ĐH Y Hà Nội.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 21.0179,
                'longitude'     => 105.8412,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Thanh Xuân',
                'ward_name'     => 'Phường Thanh Xuân Trung',
                'address_detail'=> 'Thanh Xuân Trung, Thanh Xuân, Hà Nội',
                'name'          => 'Cho thuê phòng trọ 25m2 sạch sẽ, an ninh tốt - Thanh Xuân',
                'price'         => 3200000,
                'area'          => 25,
                'description'   => 'An ninh 24/7, giờ giấc tự do, không chung chủ. Gần Trung tâm thương mại Royal City.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 20.9957,
                'longitude'     => 105.8113,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Tây Hồ',
                'ward_name'     => 'Phường Quảng An',
                'address_detail'=> 'Quảng An, Tây Hồ, Hà Nội',
                'name'          => 'Cho thuê phòng trọ khu vực Tây Hồ, view hồ',
                'price'         => 5000000,
                'area'          => 30,
                'description'   => 'Môi trường sống trong lành, gần hồ Tây, đầy đủ tiện ích. View hồ cực đẹp.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Ban công'],
                'latitude'      => 21.0590,
                'longitude'     => 105.8258,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Bắc Từ Liêm',
                'ward_name'     => 'Phường Cổ Nhuế 2',
                'address_detail'=> 'Cổ Nhuế, Bắc Từ Liêm, Hà Nội',
                'name'          => 'Phòng trọ khép kín tại Bắc Từ Liêm, gần ĐH Mỏ Địa Chất',
                'price'         => 2200000,
                'area'          => 20,
                'description'   => 'Thích hợp cho sinh viên Học viện Tài chính và ĐH Mỏ Địa Chất. Gần QL32.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 21.0672,
                'longitude'     => 105.7796,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Nam Từ Liêm',
                'ward_name'     => 'Phường Mỹ Đình 1',
                'address_detail'=> 'Mỹ Đình 1, Nam Từ Liêm, Hà Nội',
                'name'          => 'Cho thuê phòng trọ cao cấp tại Mỹ Đình, Nam Từ Liêm',
                'price'         => 4500000,
                'area'          => 35,
                'description'   => 'Phòng rộng, đầy đủ đồ, gần bến xe Mỹ Đình và sân Mỹ Đình.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Tủ lạnh', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 21.0219,
                'longitude'     => 105.7795,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Gia Lâm',
                'ward_name'     => 'Thị trấn Trâu Quỳ',
                'address_detail'=> 'Trâu Quỳ, Gia Lâm, Hà Nội',
                'name'          => 'Phòng trọ giá rẻ tại Gia Lâm, gần VinUniversity',
                'price'         => 1800000,
                'area'          => 25,
                'description'   => 'Phòng sạch sẽ, không gian thoáng đãng khu vực Gia Lâm. Gần Học viện Nông nghiệp VN.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 21.0080,
                'longitude'     => 105.9368,
            ],
            [
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Cầu Giấy',
                'ward_name'     => 'Phường Dịch Vọng',
                'address_detail'=> 'Dịch Vọng, Cầu Giấy, Hà Nội',
                'name'          => 'Phòng trọ cao cấp full nội thất ngay trung tâm Cầu Giấy',
                'price'         => 6000000,
                'area'          => 30,
                'description'   => 'Thang máy, hầm để xe rộng, full đồ đạc cao cấp. Vị trí trung tâm Cầu Giấy.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Tủ lạnh', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Thang máy'],
                'latitude'      => 21.0365,
                'longitude'     => 105.7920,
            ],

            // ==================== TP. HỒ CHÍ MINH (SÀI GÒN) ====================
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 10',
                'ward_name'     => 'Phường 14',
                'address_detail'=> 'Phường 14, Quận 10, Hồ Chí Minh',
                'name'          => '1.8 triệu/tháng - Phòng dorm 1 người gần ĐH HUFLIT, Y Khoa Phạm Ngọc Thạch Q10',
                'price'         => 1800000,
                'area'          => 15,
                'description'   => 'Chính chủ cho thuê phòng trọ 1 người sạch sẽ tại Quận 10. Gần ĐH HUFLIT và BV Phạm Ngọc Thạch.',
                'amenities'     => ['Wifi', 'Chỗ để xe', 'Camera an ninh', 'Tự do giờ giấc'],
                'latitude'      => 10.7731,
                'longitude'     => 106.6650,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 11',
                'ward_name'     => 'Phường 9',
                'address_detail'=> 'Phường 9, Quận 11, Hồ Chí Minh',
                'name'          => 'Phòng mới tuyệt đẹp, 40m2, ấm cúng - Quận 11',
                'price'         => 1800000,
                'area'          => 40,
                'description'   => 'Phòng cho 4 bạn nữ ở ghép, đẹp và thân thiện. Phù hợp sinh viên ở ghép.',
                'amenities'     => ['WC chung', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 10.7630,
                'longitude'     => 106.6543,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Tân Phú',
                'ward_name'     => 'Phường Tây Thạnh',
                'address_detail'=> 'Lương Thế Vinh, Tân Phú, Hồ Chí Minh',
                'name'          => 'Cho thuê phòng trọ mới sơn sửa - Lương Thế Vinh, Tân Phú',
                'price'         => 1900000,
                'area'          => 20,
                'description'   => 'Phòng mới sửa, sạch sẽ thoáng mát tại Tân Phú. Gần chợ Tân Phú.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 10.7916,
                'longitude'     => 106.6246,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Thành phố Thủ Đức',
                'ward_name'     => 'Phường Linh Đông',
                'address_detail'=> 'Kha Vạn Cân, Linh Đông, Thủ Đức, Hồ Chí Minh',
                'name'          => 'Sleepbox cao cấp mới 100% - Kha Vạn Cân, Thủ Đức',
                'price'         => 1200000,
                'area'          => 10,
                'description'   => 'Mô hình sleepbox riêng tư, hiện đại cho các bạn trẻ. Gần ĐH Quốc Gia TP.HCM.',
                'amenities'     => ['Wifi', 'Điều hòa', 'Camera an ninh', 'Chỗ để xe'],
                'latitude'      => 10.8451,
                'longitude'     => 106.7403,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 10',
                'ward_name'     => 'Phường 11',
                'address_detail'=> 'Phường 11, Quận 10, Hồ Chí Minh',
                'name'          => 'Phòng trọ Quận 10 mới xây đầy đủ tiện nghi',
                'price'         => 4000000,
                'area'          => 25,
                'description'   => 'Phòng đẹp, ngay trung tâm Q10 thuận tiện di chuyển. Gần chợ dân sinh.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 10.7731,
                'longitude'     => 106.6650,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 7',
                'ward_name'     => 'Phường Tân Phong',
                'address_detail'=> 'Tân Phong, Quận 7, Hồ Chí Minh',
                'name'          => 'Cho thuê phòng trọ Quận 7 gần Lotte Mart',
                'price'         => 3500000,
                'area'          => 20,
                'description'   => 'Phòng an ninh, gần siêu thị Lotte Mart, khu vực cao ráo không ngập. Khu đô thị mới.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 10.7328,
                'longitude'     => 106.7187,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 3',
                'ward_name'     => 'Phường 7',
                'address_detail'=> 'Phường 7, Quận 3, Hồ Chí Minh',
                'name'          => 'Phòng trọ Quận 3 đầy đủ nội thất, gỗ sang trọng',
                'price'         => 5000000,
                'area'          => 30,
                'description'   => 'Ngay trung tâm Q3, nội thất gỗ sang trọng. Gần Dinh Độc Lập, Công viên Tao Đàn.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Tủ lạnh', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 10.7748,
                'longitude'     => 106.6939,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Bình Thạnh',
                'ward_name'     => 'Phường 26',
                'address_detail'=> 'Phường 26, Bình Thạnh, Hồ Chí Minh',
                'name'          => 'Cho thuê phòng trọ quận Bình Thạnh gần ĐH HUTECH',
                'price'         => 3200000,
                'area'          => 22,
                'description'   => 'Tiện cho sinh viên HUTECH, Ngoại Thương. Gần ngã tư Bình Triệu.',
                'amenities'     => ['WC riêng', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 10.8183,
                'longitude'     => 106.7160,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Phú Nhuận',
                'ward_name'     => 'Phường 17',
                'address_detail'=> 'Phường 17, Phú Nhuận, Hồ Chí Minh',
                'name'          => 'Phòng trọ quận Phú Nhuận sạch sẽ an ninh, khu dân văn minh',
                'price'         => 4500000,
                'area'          => 28,
                'description'   => 'Khu dân cư văn minh, an ninh, phòng rộng rãi. Gần chợ Phú Nhuận.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 10.7998,
                'longitude'     => 106.6820,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Tân Bình',
                'ward_name'     => 'Phường 13',
                'address_detail'=> 'Phường 13, Tân Bình, Hồ Chí Minh',
                'name'          => 'Cho thuê phòng trọ quận Tân Bình gần sân bay Tân Sơn Nhất',
                'price'         => 3800000,
                'area'          => 25,
                'description'   => 'Thuận tiện cho nhân viên sân bay, sạch sẽ. Gần Sân bay Tân Sơn Nhất.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 10.7980,
                'longitude'     => 106.6568,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 1',
                'ward_name'     => 'Phường Bến Nghé',
                'address_detail'=> 'Bến Nghé, Quận 1, Hồ Chí Minh',
                'name'          => 'Phòng trọ Quận 1 trung tâm thành phố, đầy đủ tiện nghi',
                'price'         => 6000000,
                'area'          => 20,
                'description'   => 'Vị trí cực vip trung tâm thành phố, đầy đủ tiện ích. Gần Bến Bạch Đằng, Nhà hát TP.',
                'amenities'     => ['WC riêng', 'Điều hòa', 'Tủ lạnh', 'Nước nóng', 'Wifi', 'Chỗ để xe', 'Camera an ninh'],
                'latitude'      => 10.7769,
                'longitude'     => 106.7009,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 5',
                'ward_name'     => 'Phường 11',
                'address_detail'=> 'Phường 11, Quận 5, Hồ Chí Minh',
                'name'          => 'Cho thuê phòng trọ Quận 5 gần ĐH Y Dược TP.HCM',
                'price'         => 3000000,
                'area'          => 18,
                'description'   => 'Khu vực sầm uất, an ninh tốt, gần các bệnh viện và trường đại học Y Dược.',
                'amenities'     => ['WC riêng', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 10.7540,
                'longitude'     => 106.6618,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 8',
                'ward_name'     => 'Phường 4',
                'address_detail'=> 'Phường 4, Quận 8, Hồ Chí Minh',
                'name'          => 'Phòng trọ Quận 8 giá sinh viên, tự do giờ giấc',
                'price'         => 2200000,
                'area'          => 20,
                'description'   => 'Giá rẻ, giờ giấc tự do, có chỗ để xe máy. Gần cầu Chữ Y.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 10.7425,
                'longitude'     => 106.6788,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 6',
                'ward_name'     => 'Phường 7',
                'address_detail'=> 'Phường 7, Quận 6, Hồ Chí Minh',
                'name'          => 'Phòng trọ Quận 6 mới sửa, thoáng mát gần chợ Bình Tây',
                'price'         => 2600000,
                'area'          => 24,
                'description'   => 'Phòng sơn mới, thoáng đãng, gần chợ Bình Tây và chợ An Đông.',
                'amenities'     => ['WC riêng', 'Nước nóng', 'Wifi', 'Chỗ để xe'],
                'latitude'      => 10.7488,
                'longitude'     => 106.6375,
            ],
            [
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 12',
                'ward_name'     => 'Phường Tân Chánh Hiệp',
                'address_detail'=> 'Tân Chánh Hiệp, Quận 12, Hồ Chí Minh',
                'name'          => 'Cho thuê phòng trọ Quận 12 gần CVPM Quang Trung',
                'price'         => 1800000,
                'area'          => 20,
                'description'   => 'Giá rẻ, thích hợp sinh viên hoặc người đi làm ở CVPM Quang Trung. Gần QL1A.',
                'amenities'     => ['WC riêng', 'Wifi', 'Chỗ để xe', 'Tự do giờ giấc'],
                'latitude'      => 10.8698,
                'longitude'     => 106.6468,
            ],
        ];

        $provinceToLandlord = [
            'Tỉnh Nghệ An'            => $landlords['Tỉnh Nghệ An'],
            'Thành phố Hà Nội'        => $landlords['Thành phố Hà Nội'],
            'Thành phố Hồ Chí Minh'   => $landlords['Thành phố Hồ Chí Minh'],
        ];

        foreach ($rooms as $data) {
            $landlord = $provinceToLandlord[$data['province_name']];

            Room::updateOrCreate(
                [
                    'name'        => $data['name'],
                    'landlord_id' => $landlord->id,
                ],
                [
                    'price'             => $data['price'],
                    'area'              => $data['area'],
                    'floor'             => 1,
                    'description'       => $data['description'],
                    'amenities'         => $data['amenities'],
                    'electricity_price' => 3800,
                    'water_price'       => 15000,
                    'service_fee'       => 50000,
                    'status'            => $data['status'] ?? 'available',
                    'approval_status'   => 'approved',
                    'province_name'     => $data['province_name'],
                    'district_name'     => $data['district_name'],
                    'ward_name'         => $data['ward_name'],
                    'address_detail'    => $data['address_detail'],
                    'latitude'          => $data['latitude'] + (rand(-20, 20) / 10000),
                    'longitude'         => $data['longitude'] + (rand(-20, 20) / 10000),
                ]
            );
        }

        $this->command->info('   ✅ Đã tạo ' . count($rooms) . ' phòng trọ thực từ phongtro123.com');
    }
}
